export enum AuthenticationEventType {
  LOGIN_SUCCEEDED,
  LOGIN_FAILED,

  MFA_CHALLENGE_CREATED,
  MFA_VERIFIED,

  REFRESH_TOKEN_ISSUED,
  REFRESH_TOKEN_ROTATED,
  REFRESH_TOKEN_REVOKED,

  SESSION_REVOKED,

  LOGOUT,
  LOGOUT_ALL,
}