-- AlterTable
ALTER TABLE `authentication_events` MODIFY `type` ENUM('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'SESSION_REVOKED', 'API_KEY_CREATED', 'API_KEY_REVOKED', 'PASSWORD_CHANGED', 'REFRESH_TOKEN_ROTATED', 'MFA_CHALLENGE_CREATED') NOT NULL;
