-- AlterTable
ALTER TABLE `authentication_events` MODIFY `type` ENUM('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'SESSION_REVOKED', 'API_KEY_CREATED', 'API_KEY_REVOKED', 'API_KEY_ROTATED', 'PASSWORD_CHANGED', 'REFRESH_TOKEN_ROTATED', 'MFA_CHALLENGE_CREATED', 'MFA_VERIFIED', 'REFRESH_TOKEN_ISSUED', 'REFRESH_TOKEN_REVOKED', 'LOGOUT_ALL') NOT NULL;
